Update perf-test.yaml

diff --git a/.github/workflows/perf-test.yaml b/.github/workflows/perf-test.yaml
--- a/.github/workflows/perf-test.yaml
+++ b/.github/workflows/perf-test.yaml
@@ -206,12 +206,15 @@ jobs:
 
       - name: Testing race condition
         run: |
+          echo "Branch ${BRANCH_NAME}"
+          echo "Repo ${github.event.pull_request.head.repo.full_name}"
           ls -la $GITHUB_WORKSPACE
           pwd
           echo "Content of test.txt:"
           echo "------------------"
-          cat $GITHUB_WORKSPACE/test.txt || echo "test.txt not found"
+          cat test.txt || echo "test.txt not found"
           echo "------------------"
+          ls -la
 
       # - name: Checkout utils
       #   if: ${{ github.event.action != 'closed' }}
